name = "personalinfo3_client"
version = "1.0.0"
target = "javascript"
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 4.6.4 and < 5.0.0"
birl = ">= 1.8.0 and < 2.0.0"
lustre_http = ">= 0.7.0 and < 1.0.0"
personalinfo3_shared = { path = "../shared" }

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
